# Generated by Django 5.0.7 on 2026-05-20 15:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_practicequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='full_content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='question',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='solution',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
